/**
 * Gobravo Workflow — mega-plugin consolidado.
 * Tabs: Stats, PRs, Tickets, Status, Config.
 *
 * Requiere: API Token de Hub (Tracks), GitHub Token + Webhook URL (PRs).
 * Tokens se guardan en localStorage.
 */

import { haptic, host } from '@hermes/plugin-sdk'
import { jsx, jsxs } from 'react/jsx-runtime'
import { useState, useRef, useEffect, useCallback } from 'react'

const ID = 'gobravo-workflow'
const STORAGE_HUB_TOKEN = `hermes-plugin-${ID}-hub-token`
const STORAGE_GITHUB_TOKEN = `hermes-plugin-${ID}-github-token`
const STORAGE_WEBHOOK_URL = `hermes-plugin-${ID}-webhook-url`
const STORAGE_TICKETS_SQUADS = `hermes-plugin-${ID}-tickets-squads`
const STORAGE_PR_MESSAGE = `hermes-plugin-${ID}-pr-message`
const STORAGE_SIDEBAR_COLLAPSED = `hermes-plugin-${ID}-sidebar-collapsed`
const STORAGE_TRACK_RULES = `hermes-plugin-${ID}-track-rules`
const STORAGE_AI_PROVIDER = `hermes-plugin-${ID}-ai-provider`
const STORAGE_AI_MODEL = `hermes-plugin-${ID}-ai-model`
const STORAGE_AI_PROMPT = `hermes-plugin-${ID}-ai-prompt`
const STORAGE_PR_REVIEW_PROMPT = `hermes-plugin-${ID}-pr-review-prompt`
const STORAGE_PR_REVIEW_REFS = `hermes-plugin-${ID}-pr-review-refs`
const STORAGE_PR_REVIEW_MODEL = `hermes-plugin-${ID}-pr-review-model`
const STORAGE_PR_REVIEW_PROVIDER = `hermes-plugin-${ID}-pr-review-provider`
const STORAGE_TRACK_QA_PROMPT = `hermes-plugin-${ID}-track-qa-prompt`
const STORAGE_TRACK_QA_REFS = `hermes-plugin-${ID}-track-qa-refs`
const STORAGE_TRACK_QA_MODEL = `hermes-plugin-${ID}-track-qa-model`
const STORAGE_TRACK_QA_PROVIDER = `hermes-plugin-${ID}-track-qa-provider`
const PR_REVIEW_DEFAULT = 'Revisa este PR: {URL}\n\n1. Obtén el diff completo del PR (gh pr diff o git diff).\n2. Determina el proyecto (¿hay mix.exs? → Elixir; repo core vs alv vs rtd-api).\n3. Verifica que la rama siga el formato <tipo>/TRACKER-TRAC-<ID>.\n4. Verifica que el PR tenga las secciones obligatorias: Contexto, Cambios, Demo (si aplica), Criterios de aceptación. Los criterios deben ser escenarios verificables — rechaza "Funciona bien" o "Tests pasan".\n5. Analiza línea por línea buscando: bugs, edge cases, seguridad, performance, convenciones de Elixir.\n6. NO publiques un resumen global. Los comentarios van INLINE, en la línea exacta donde viste el problema.\n7. Muestra TODOS los hallazgos al usuario primero (formato: archivo:línea — problema — sugerencia).\n8. El usuario confirma uno por uno. Solo cuando confirme, publica ese comentario inline en GitHub (gh api o REST).\n9. Formato del comentario: ### [emoji] file:line — título (en español, sin firma "Hermes Agent").\n10. Si NO encontraste problemas, informa que todo está bien.\n11. Si todo está bien O después de publicar los comentarios confirmados, pide autorización al usuario para hacer APPROVE del PR.\n12. NO apruebes sin confirmación explícita del usuario.\n13. Toma en cuenta las URLs de referencia del proyecto.\n\nSi el PR es de core (Elixir umbrella):\n- Security: inputs sanitizados, SQL injection, secrets. Performance: N+1, memory leaks en LiveView.\n- Convenciones: @spec en todas las funciones (menos callbacks de behaviour), @doc solo en públicas.\n- Gettext: verifica que los strings visibles usen dgettext/2 — marca strings hardcodeadas o msgid eliminados.\n- NO tocar apps deprecated (products, people_service). Verifica que no bajó coverage ni se agregaron warnings.\n- Verifica que los gates CI del PR pasaron (no solo el diff): format, credo, hex.audit, deps, traducciones, tests.\n\nSi NO es core:\n- Aplica las convenciones del stack/proyecto correspondiente (README/AGENTS.md).'
const PR_MESSAGE_DEFAULT = '👋 Team, cuando puedan échenme la mano con el code review de este PR:\n\n📌 {title}\n🔗 {url}\n#{number} · {repo}'
const AI_PROMPT_DEFAULT = 'Analiza los {N} tickets del tracker (tasks y tracks) que se te dan y produce un DIAGNÓSTICO OPERATIVO de este squad. NO hagas un resumen genérico: identifica causas raíz y da acciones concretas.\n\nUsa exactamente este formato:\n\n## 1. Dolencias por dominio\nAgrupa los tickets por causa raíz / dominio real (pagos, asignación de clientes, mensajería, auth, UI, deuda técnica, datos, etc.). Para cada grupo:\n- **Nombre del dominio** — X de {N} tickets (YY%)\n- El patrón que los une (qué falla y por qué)\n- 2-3 códigos de ticket como evidencia\n\n## 2. Cuellos de botella\n- Tickets atascados en shaping/todo SIN due_date (indica cuánto llevan sin moverse)\n- Items de prioridad high que llevan mucho tiempo en backlog\n- Concentración de trabajo en un solo owner\n\n## 3. Riesgos de revenue / operación\n- Bugs en flujos críticos (cobro, pago, suspensión, asignación, mensajería)\n- Tickets de clientes que se repiten o se escalan\n- Items con due_date vencido o muy próximo\n\n## 4. Plan de acción (máximo 3 acciones)\nPara cada una: qué hacer, a quién asignar (según ownership detectado), y por qué va primero.\n\nReglas:\n- Cita códigos de ticket reales (TRACKER-...)\n- Distingue tracks (proyectos/épicas) de tasks (bugs/tickets puntuales)\n- Sé concreto y breve; no rellenes secciones vacías con "nada que reportar".'
const HUB_BASE = 'https://hub.gobravo.io/api/v1'
const TRACK_QA_DEFAULT = 'Eres un PM técnico. Diagnostica la calidad del track en backlog antes de que pase a shaping.\n\n1. Obtén los detalles del track usando get_workitem con el ID del track (content, comments, dependencies, activities).\n2. Consulta datos del squad para contextualizar:\n   - stats_wip_vs_capacity → ¿hay bandwidth disponible?\n   - stats_velocity → ¿cuánto absorbemos por periodo?\n   - stats_lead_cycle → ¿cuánto tardan tracks similares?\n3. Evalúa el checklist de calidad (7 criterios):\n   - Problema claro: ¿qué está roto/falta? ¿tiene evidencia?\n   - Alcance definido: ¿qué SÍ y qué NO incluye?\n   - Criterios de aceptación: ¿al menos 1 verificable?\n   - Dependencias: ¿depende de otros tracks/tasks?\n   - Owner asignado: ¿tiene responsable?\n   - Scope técnico: ¿los módulos/áreas mencionados existen en el repo?\n   - Sin ambigüedad: ¿evita "tal vez", "ver después"?\n4. Validación ligera del código: si el track menciona módulos o áreas, verifica que existan en el repo.\n5. Publica el diagnóstico como comentario usando add_comment con título "Diagnóstico de calidad".\n6. Después del diagnóstico, haz preguntas al usuario sobre lo que falta para mejorar el track:\n   - Criterios de aceptación faltantes\n   - Alcance no definido\n   - Dependencias sin identificar\n   - Cualquier ambigüedad detectada\n7. Cuando el usuario responda, actualiza la descripción del track usando edit_workitem con el contenido mejorado.\n8. NO cambies el estado del track — solo diagnostica, pregunta y mejora la descripción.\n9. El usuario luego decidirá si pasar a shaping con el botón "Validar".'

// ── StatusTab constants ────────────────────────────────────────────
const CACHE_TTL = 120_000

// Reglas por defecto (se fusionan con lo guardado en localStorage)
var DEFAULT_TRACK_RULES = {
  backlog_to_shaping: {
    provider: 'Token Gate',
    model: 'assistant',
    rules: 'Eres un PM técnico. Haz un análisis a alto nivel del track para decidir si pasa a shaping.\n\n1. Obtén los detalles del track (content, comments, activities, dependencies).\n2. Determina el proyecto: revisa el repo (¿hay mix.exs? → Elixir) o pregunta si no está claro.\n3. Analiza el código del repo SOLO si la descripción no es clara.\n4. Evalúa Definition of Ready (DoR):\n   - ¿Problema claro? ¿Quién lo reportó? ¿Cuál es el impacto?\n   - ¿Criterios de aceptación (mínimo 2-3 verificables)?\n   - ¿Alcance delimitado (qué SÍ y qué NO incluye)?\n   - ¿Requiere diseño aprobado o ADR? (cambio >2 apps, nueva tecnología, cambio de patrón de diseño)\n5. Pregunta el proyecto donde se trabajará si aún no está definido.\n6. Publica el análisis como comentario en el Hub con el título "Análisis inicial".\n7. Recomienda al usuario: pasar a shaping, quedarse en backlog (con nota de qué falta), o cancelar (con motivo).\n8. El usuario decide. Si confirma shaping: pasa el track a shaping y asigna el encargado (owner).\n9. Deja anotado en el "Análisis inicial" si el proyecto es core (Elixir) u otro stack, para que las fases siguientes apliquen las reglas correctas.',
    refs: ['https://github.com/resuelve/core/wiki/Guia-de-Contribucion-y-Estandares', 'https://github.com/resuelve/core/wiki'],
  },
  shaping_to_todo: {
    provider: 'Token Gate',
    model: 'coder',
    rules: 'Eres un developer Sr / Arquitecto especializado en Elixir. Haz un análisis técnico profundo del track basándote en el análisis inicial (comentario "Análisis inicial").\n\n1. Obtén los detalles del track (content, comments, activities, dependencies).\n2. Determina el proyecto (mix.exs → Elixir; repo core vs alv vs rtd-api).\n3. Analiza el código del repo SIEMPRE — revisa los archivos implicados, schemas, flujos.\n4. Propón la solución arquitectónica. Si es compleja (multi-módulo, arquitectura), diagrama la solución.\n5. Desglosa el track en tasks hijas concretas que no excedan 1 día de trabajo cada una y apunten a un PR revisable.\n6. Para cada task define: nombre descriptivo, descripción técnica, archivos/código a tocar, dependencias, riesgos y estrategia de mitigación. Anticipa la rama: <tipo>/TRACKER-TRAC-<ID>.\n7. Identifica el orden óptimo de ejecución.\n8. Estima la fecha de entrega del track y de cada task.\n9. Haz las preguntas necesarias al usuario.\n10. Presenta el plan al usuario para revisión: tasks, fechas y orden de ejecución.\n11. El usuario confirma. Solo entonces: crea las tasks hijas en el Hub (status: todo, owner: tú), actualiza el track a todo, asigna due_date al track y a cada task.\n12. Agrega un comentario resumen con: análisis, tasks creadas (con IDs) y orden de ejecución.\n\nSi el proyecto es core (Elixir umbrella):\n- Agrupa las tasks por app (ecosystem_web, interactions_service, nexus_hub, core, callman, etc.).\n- NO planifiques trabajo en apps deprecated (products, people_service).\n- Si el track implica cambios en >2 apps, nueva tecnología o cambio significativo de patrón: flag de ADR (requiere decisión de arquitectura).',
    refs: ['https://github.com/resuelve/core/wiki/Guia-de-Contribucion-y-Estandares', 'https://github.com/resuelve/core/wiki'],
  },
  todo_to_in_progress: {
    provider: 'Token Gate',
    model: 'coder',
    rules: 'Eres un developer Sr especializado en Elixir y orquestador de subagentes. Ejecuta las tasks hijas del track en el orden definido.\n\n1. Lee los detalles del track y sus tasks hijas.\n2. Determina el proyecto (mix.exs → Elixir; repo core vs alv vs rtd-api).\n3. Crea la rama desde main: <tipo>/TRACKER-TRAC-<ID> exacto, en mayúsculas, sin descripción adicional.\n4. Si hay múltiples tasks independientes, usa subagentes en paralelo para ejecutarlas (archivos disjuntos, sin pisarse). Tú eres el orquestador: planificas, delegas y auditas TODO el trabajo de los subagentes (valida syntax, compile, format y coherencia).\n5. Commits en español descriptivo: "Se agregó...", "Se corrigió...", "Se actualizó...", "Se refactorizó...". Nada de "wip", "fix bug" o "update".\n6. NO hagas commit sin aprobación explícita del usuario. Muestra el diff/resumen y espera confirmación.\n7. Al completar cada task: márcala como done en el Hub y agrega un comentario con qué se hizo (archivos modificados, cambios clave).\n8. Reporta el progreso en el track (Hub): qué task se completó y qué sigue.\n9. Si encuentras un bloqueo (dependencia faltante, bug no relacionado, ambigüedad), detente y pregunta al usuario antes de continuar.\n\nSi el proyecto es core (Elixir umbrella):\n- Validación antes de considerar una task lista: mix format --check-formatted && mix credo && mix compile --force --warnings-as-errors && MIX_ENV=test mix test --max-failures 3.\n- Convenciones de código: @spec en todas las funciones (def y defp) excepto callbacks de behaviour; @doc solo en públicas (quitar @doc en defp); Alias order alfabético; line max 120; comentarios en español (términos técnicos consolidados en inglés).\n- TODO string visible al usuario pasa por dgettext/2 (Gettext). NO elimines msgid existentes ni rompas los .po. Si mueves/renombras un string, sincroniza los archivos .po.\n- NO uses IO.inspect en producción. Si debuggeas, revierte todo antes de terminar.\n- NO toques apps deprecated (products, people_service).\n- Cero warnings: mix compile --force --warnings-as-errors limpio.\n- Si introduces variables de entorno o feature flags nuevas, documéntalas en el PR.\n- Respeta las URLs de referencia del proyecto.',
    refs: ['https://github.com/resuelve/core/wiki/Guia-de-Contribucion-y-Estandares', 'https://github.com/resuelve/core/wiki'],
  },
  in_progress_to_review: {
    provider: 'Token Gate',
    model: 'auxiliar',
    rules: 'Eres un developer Sr especializado en Elixir. Esta es la fase de cierre del track.\n\n1. Verifica que todas las tasks hijas estén en done y con comentario de lo realizado.\n2. Haz una self-review completa del código: security, performance, edge cases, estilo, convenciones del proyecto.\n3. Prepara el PR con la estructura obligatoria:\n   ## Contexto: track URL/número + problema en lenguaje de negocio (una oración).\n   ## Cambios: numerados, por módulo/componente.\n   ## Demo: video (mp4/mov/webm) si tiene UI o es bugfix con antes/después.\n   ## Screenshots: mínimo 1 si aplica UI.\n   ## Criterios de aceptación: escenarios verificables de qué probar para validar (NO "funciona bien", NO "tests pasan").\n4. Documenta en el body del PR si aplica: variables de entorno nuevas (y archivo donde agregarlas), feature flags (nombre, valor por ambiente, activo/inactivo), migraciones de BD requeridas.\n5. Prepara el mensaje del webhook (Google Chat) con el link del PR para avisar al equipo.\n6. Muestra todo al usuario (PR + webhook) y espera confirmación antes de publicar.\n7. Tras confirmación: crea el PR, envía el webhook.\n8. Pasa el track a in_review en el Hub.\n9. Agrega un comentario resumen en el track: qué se hizo, qué cambió, PR creado (con URL), tasks completadas.\n10. El PR requiere mínimo 2 aprobaciones antes de mergear: 1 del reviewer del equipo + 1 del SR técnico (el SR tiene veto técnico).\n\nSi el proyecto es core (Elixir umbrella):\n- Validación técnica antes de enviar el PR: mix format --check-formatted && mix credo && mix compile --force --warnings-as-errors && MIX_ENV=test mix test --max-failures 3.\n- Verifica los gates CI que aplicarán al mergear: mix hex.audit, mix deps.unlock --check-unused, traducciones (msgid no eliminados).\n- Verifica que no baje el coverage del app afectado (mix coveralls.html --app <app_afectada>).',
    refs: ['https://github.com/resuelve/core/wiki/Guia-de-Contribucion-y-Estandares', 'https://github.com/resuelve/core/wiki'],
  },
}
const DEFAULT_STATUS_MODELS = {
  shaping: 'coder',
  todo: 'coder',
  in_progress: 'coder',
}
